### ISSUE TITLE
should_render_template fails with partials

### ISSUE THREAD

**Issue by assaf** [carlosbrando/remarkable#1]
render_template_matcher.rb line 23:
     path_and_file(response.rendered[:partials].keys.first).join("/_")
should be:
     path_and_file(@response.rendered[:partials].keys.first).join("/_")

**Comment by josevalim** [comment]
Moved to: http://carlosbrando.lighthouseapp.com/projects/19775-remarkable/tickets/43-render_template-does-not-work-with-partials
