### ISSUE TITLE
rspec 2 and rails 3

### ISSUE THREAD

**Issue by ramon** [carlosbrando/remarkable#15]
Já existe algum trabalho pra torna o ramarkable compatível com o rspec 2?

**Comment by carlosbrando** [comment]
O RSpec 2 ainda não foi finalizado. Mas ainda não iniciamos nenhum trabalho neste sentido. Estamos procurando por programadores interessados em fazer isso.

**Comment by ramon** [comment]
eu comecei a mexer pra fazer compatível com rspec 2. assim que eu tive alguma coisa funcionando eu subo o branch no meu fork e aviso a vcs.

**Comment by carlosbrando** [comment]
Excelente!

**Comment by issueapp** [comment]
Remarkable doesn't work with rspec2 at the moment, Any words on Rspec2/rails3 support?

**Comment by carlosbrando** [comment]
We are looking for volunteers to upgrade the project.

**Comment by hosh** [comment]
I am volunteering since I really need it for this current paid project, but I'd like to know where are some good places to start.

**Comment by speedmax** [comment]
+1

I can contribute some time on this too, only problem is.. 
probably need carlos's  help to
1. point us to right direction where to start
2. someone to work out what is been changed for rspec2 matchers, how it's load and everything.

Anyone else?

**Comment by carlosbrando** [comment]
The first step is to create a new fork and make the project works with Rails 3 and RSpec 2. 

I did not intend to continue the project, but with an enough people working on it we can make it work.

I think you two can fork the project and work on it. What do you think?

**Comment by hosh** [comment]
Hey, sorry for the late reply. In the past three days, I have been working on a Remarkable fork for Rails 3 / Rspec 2. My intention is to make a sparkfly-remarkable 4.0 fork, unless Carlos officially passes the torch. I've started by dropping Remarkabe 3.latest into a Rails3 environment and just run the specs and fixing things as I go along. I've been updating a thread on the Remarkable Google Group as I go along. 

The current issue relates to the fact that ActiveModel no longer has a 2.3.5 compatible I18n error messages. In fact, there is an activemodel_errors project that is attempting to refactor that. Seems that, even though there are people who care about I18n, they care more about the core subset working.

I have a fork running right now at hosh/remarkable under the rspec2 branch and some code I have not yet pushed up.

**Comment by carlosbrando** [comment]
Ho-Sheng Hsiao, I added you as a committer on the project and if you're willing I pass the torch to your hands. What do you have to say about it?

**Comment by hosh** [comment]
Sure Carlos. Would you mind terribly if I also added a remarkable/remarkable fork? Also, what about the gemcutter account?

For speedmax and anyone else who wants to contrib, here are my current thoughts:
- Split Remarkable::ActiveRecord -> ActiveModel, and ActiveRecord macros
- Publish this as a Remarkable 4.0 pre 
- If there are enough people still needing Remarkable 3.x on Rails 2, we need to find maintainers.
- I also need a good solution for Arel matchers.

Ah, I'd prefer it if we discuss this in greater detail on the Google Groups page.

**Comment by reMarkable-xx** [comment]
Ok, I've created a new remarkable/remarkable repository. Then I will disable the old repository soon.

I think we can create a new branch for the current version for compatibility and just continue maintaining the project in this branch when necessary. Meanwhile we use the master to develop the new version without think in compatibility.

About gemcutter, do you know any way of two people to manage the same gem?

Although I'm really out of time, but I'll try to answer your questions on the Google Group.

**Comment by hosh** [comment]
Sounds reasonable about the compatibility gem. I'll look for how to have multi-users for the same gem.

We'll also need to move the issues over. As for disabling the carlosbrando/remarkable, I think you may have to ask Github support about it, so all the registered forks comes off of that.

**Comment by hosh** [comment]
@Carlos the command is gem owner <email>. Use ['hosheng', 'hsiao']*"." + "@gmail.com" You will probably need rubygems 1.3.6 and maybe the gemcutter gem.

**Comment by carlosbrando** [comment]
Owner added successfully.

I will send a message to github support and see if it's possible.

**Comment by hosh** [comment]
Carlos, I noticed it got moved over to remarkable/remarkable. What about the issue tracker, are they still working on it?

**Comment by carlosbrando** [comment]
Posted by Tekkub:
We can change which repo is the root, but we can't move the non-repo data between repos.

**Comment by hosh** [comment]
Ok. What about enabling the issues on the remarkable/remarkable one, and/or sending me the credentials? Either is fine. I can add the stuff with the code right now, and otherwise, tell people to move the issues themselves. (So the ones people really care about will get reported).

**Comment by carlosbrando** [comment]
Sorry. I enabled issues right now.

Did you receive notifications in your e-mail?

**Comment by rscarvalho** [comment]
Any updates on this?
