### ISSUE TITLE
I18n depracation warning on rails 2.3.9.pre

### ISSUE THREAD

**Issue by morgoth** [carlosbrando/remarkable#16]
Running specs on rails 2.3.9.pre warns:

The {{key}} interpolation syntax in I18n messages is deprecated. Please use %{key} instead

**Comment by sdillard** [comment]
Just to note that I am hitting this also.  My understanding is that there were patches in rails 3 for this and it is fixed in 0.4+ of i18n, but I had other issues when I tried to go to the 0.4 version of the gem.

**Comment by ssojoodi** [comment]
I'm using Rails 2.3.5, i18n 0.4.2, and had the same problem.  I resolved it by changing all instances of '{{' / '}}' to '%{' / '}' respectively in the following files (remarkable)

./remarkable-3.1.13/locale/en.yml
./remarkable_activerecord-3.1.13/locale/en.yml
./remarkable_rails-3.1.13/locale/en.yml
