### ISSUE TITLE
How about describe :xhr?

### ISSUE THREAD

**Issue by assaf** [carlosbrando/remarkable#2]
Since XHR requests are identified by header, not content type, can't use describe mime_type to spec them. Adding this option to describe would just set:
  request.env['HTTP_X_REQUESTED_WITH'] = 'XMLHttpRequest'

**Comment by josevalim** [comment]
Great tip, I will work on that! Can you send me some use cases? In other words, can you send me some tests where you were using it without remarkable?

I'm not sure if I should add a new keyword just to handle XmlHttpRequest but I definitely can add a method to handle the request object.

**Comment by josevalim** [comment]
Moved to: http://carlosbrando.lighthouseapp.com/projects/19775-remarkable/tickets/44-add-a-class-method-to-manipulate-the-request-object

**Comment by josevalim** [comment]
Discussion updated at: http://carlosbrando.lighthouseapp.com/projects/19775-remarkable/tickets/44-add-a-class-method-to-manipulate-the-request-object
