### ISSUE TITLE
(Ruby 1.9.1) uninitialized constant Remarkable::ActiveRecord (NameError) 

### ISSUE THREAD

**Issue by jachenry** [carlosbrando/remarkable#3]
spec_helper.rb
...
require 'spec/autorun'
require 'spec/rails'
require 'remarkable_rails'
...

results in the following error on ruby 1.9.1

/opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:443:in `load_missing_constant': uninitialized constant Remarkable::ActiveRecord (NameError)
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:80:in`const_missing_with_dependencies'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/remarkable_rails-3.1.10/lib/remarkable_rails/active_orm.rb:17:in `<top (required)>'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in`require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/remarkable_rails-3.1.10/lib/remarkable_rails.rb:25:in`<top (required)>'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in`require'
    from /Users/user/repos/project.com/spec/spec_helper.rb:7:in `<top (required)>'
    from /Users/user/repos/project.com/spec/models/brand_spec.rb:1:in`require'
    from /Users/user/repos/project.com/spec/models/brand_spec.rb:1:in `<top (required)>'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rspec-1.2.9/lib/spec/runner/example_group_runner.rb:15:in`load'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rspec-1.2.9/lib/spec/runner/example_group_runner.rb:15:in `block in load_files'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rspec-1.2.9/lib/spec/runner/example_group_runner.rb:14:in`each'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rspec-1.2.9/lib/spec/runner/example_group_runner.rb:14:in `load_files'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rspec-1.2.9/lib/spec/runner/options.rb:132:in`run_examples'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rspec-1.2.9/lib/spec/runner/command_line.rb:9:in `run'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rspec-1.2.9/bin/spec:5:in`<main>'

**Comment by mattsoutherden** [comment]
For me, including remarkable_activerecord before remarkable_rails fixes this problem

**Comment by jachenry** [comment]
same here.  Thanks.
