### ISSUE TITLE
typo issue when test habtm association with conditions as hash

### ISSUE THREAD

**Issue by sobrinho** [carlosbrando/remarkable#6]
See the code to understand:

<pre>should_have_and_belong_to_many :watches, :class_name => 'List', :conditions => { :pvt => false }</pre>

The output:

<pre>should have and belong to many watches with class name "List" and with conditions "pvtfalse"</pre>

I think this can be:

<pre>should have and belong to many watches with class name "List" and with conditions "pvt" equal "false"</pre>

This is just a small typo detail, if you can fix it i will appreciate :)

Best regards

**Comment by carlosbrando** [comment]
sobrinho,
I tried to reproduce the same problem and I got the following result:

<pre>
- should have and belong to many watches with class name "List" and with conditions {:pvt=>false}
</pre>


Can you give us more information to help reproduce this problem the way you say? Which version of Remarkable are you using?

**Comment by sobrinho** [comment]
Ruby: ruby 1.8.7 (2009-06-12 patchlevel 174) [x86_64-linux]
Rails: 2.3.3
Remarkable: 3.1.11
Rspec: 1.29

I changed test to fail and have the same behavior:

<pre>'User associations should have and belong to many watches with class name "List" and with conditions "pvttrue"' FAILED
Expected User records have and belong to many watches with options {:class_name=>"List", :conditions=>"pvttrue"}, got {:class_name=>"List", :conditions=>"pvtfalse"}</pre>

**Comment by josevalim** [comment]
Please provide a patch changing the i18n file to use {{inspect}} instead of {{value}}!

**Comment by sobrinho** [comment]
I can't reproduce this issue today. Was it already fixed?
