### ISSUE TITLE
#context alias referring to wrong implementation of #describe 

### ISSUE THREAD

**Issue by codebeige** [carlosbrando/remarkable#8]
The `#context` alias of `Spec::Rails::Example::ExampleGroup` is not overridden and therefore points to the original implementation of `#describe`.
Like many others I like to use `#describe` for the outermost context and `#context` for the nested ones.

As a quick fix for that I put the following in my spec_helper.rb: http://pastie.textmate.org/739391

**Comment by josevalim** [comment]
Could you please provide a patch (or a fork and pull request)?
